create TABLESPACE TBUSERS
DATAFILE 'C:\app\oracle\oradata\TBUSERS_01.dbf' 
SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M;



CREATE user ariel IDENTIFIED BY arielcobra
DEFAULT TABLESPACE TBUSERS

CREATE user guilherme IDENTIFIED BY guilhermecobra
DEFAULT TABLESPACE TBUSERS

GRANT create session, alter session, create table, create view to ariel;
GRANT create session, alter session, create table, create view to guilherme;

CREATE user regg IDENTIFIED BY regnier
DEFAULT TABLESPACE TBUSERS

GRANT create session, alter session, create table, create view to regg;

SELECT * From ALL_OBJECTS;
Select * FROM ALL_OBJECTS where object_ID <= 25;



SELECT metric_name, Value FROM V$SYSMETRIC WHERE
metric_name IN ('Database CPU Time Ratio','Database Wait Time Ratio');


SELECT *  FROM V$SYSTEM_WAIT_CLASS
Where WAIT_CLASS <> 'Idle';


SELECT SUM(TOTAL_WAITS) as SUM_TOTAL_WAITS, SUM(TIME_WAITED) as SUM_TIME_WAITED  FROM V$SYSTEM_WAIT_CLASS
Where WAIT_CLASS <> 'Idle';  

SELECT A.WAIT_CLASS, ROUND((A.TOTAL_WAITS/B.SUM_TOTAL_WAITS)*100,2) AS PCT_TOTAL_WAITS,
ROUND((A.TIME_WAITED/B.SUM_TIME_WAITED)*100,2) AS PCP_TIME_WAITED
FROM
(SELECT * FROM V$SYSTEM_WAIT_CLASS
WHERE WAIT_CLASS <> 'Idle') A,
(SELECT SUM(TOTAL_WAITS) AS SUM_TOTAL_WAITS, SUM(TIME_WAITED) AS SUM_TIME_WAITED 
FROM V$SYSTEM_WAIT_CLASS
WHERE WAIT_CLASS <> 'Idle') B;


SELECT  * FROM  V$PGA_TARGET_ADVICE;

-- verificar Consumers Groups
SELECT * FROM DBA_RSRC_CONSUMER_GROUPS;

-- Cria uma area pendente (biblioteca)
EXEC DBMS_RESOURCE_MANAGER.CREATE_PENDING_AREA;

-- criar plano de recursos
EXEC DBMS_RESOURCE_MANAGER.CREATE_PLAN (PLAN=>'DAY', COMMENT=>'Plano Diurno');

-- definir prioridades
EXEC DBMS_RESOURCE_MANAGER.CREATE_PLAN_DIRECTIVE (PLAN=>'DAY', GROUP_OR_SUBPLAN=>'SYS_GROUP', MGMT_P1=>100, COMMENT=>'Prioridade 1 para administradores do sistema');
EXEC DBMS_RESOURCE_MANAGER.CREATE_PLAN_DIRECTIVE (PLAN=>'DAY', GROUP_OR_SUBPLAN=>'INTERACTIVE_GROUP', MGMT_P2=>100, COMMENT=>'Prioridade 2 para operadores de Televendas');
EXEC DBMS_RESOURCE_MANAGER.CREATE_PLAN_DIRECTIVE (PLAN=>'DAY', GROUP_OR_SUBPLAN=>'DSS_CRITICAL_GROUP', MGMT_P3=>50, COMMENT=>'Prioridade 3 para relatórios');
EXEC DBMS_RESOURCE_MANAGER.CREATE_PLAN_DIRECTIVE (PLAN=>'DAY', GROUP_OR_SUBPLAN=>'BATCH_GROUP', MGMT_P3=>50, COMMENT=>'Prioridade 3 para processos em Batch');


-- escolher prioridade
EXEC DBMS_RESOURCE_MANAGER.CREATE_PLAN_DIRECTIVE (PLAN=>'DAY', GROUP_OR_SUBPLAN=>'DSS_CRITICAL_GROUP', MGMT_P3=>50, COMMENT=>'Prioridade 3 para relatórios');

EXEC DBMS_RESOURCE_MANAGER.CREATE_PLAN_DIRECTIVE (PLAN=>'DAY', GROUP_OR_SUBPLAN=>'BATCH_GROUP', MGMT_P3=>50, COMMENT=>'Prioridade 3 para processos em Batch');
EXEC DBMS_RESOURCE_MANAGER.CREATE_PLAN_DIRECTIVE (PLAN=>'DAY', GROUP_OR_SUBPLAN=>'OTHER_GROUPS', MGMT_P4=>100, COMMENT=>'Prioridade 4 para outros usuários');

--validar e submeter prioridade
EXEC DBMS_RESOURCE_MANAGER.VALIDATE_PENDING_AREA;

EXEC DBMS_RESOURCE_MANAGER.SUBMIT_PENDING_AREA;

--verificar se fi criado
SELECT * FROM DBA_RSRC_PLAN_DIRECTIVES WHERE PLAN = 'DAY';
--ativar
ALTER SYSTEM SET RESOURCE_MANAGER_PLAN = 'DAY';
